name: xzj_fast_flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.6
  sqflite: ^1.1.6+4
  flutter_villains: ^1.2.1
  flutter_picker: ^1.0.15
  flutter_swiper: ^1.1.6
  fluro: ^1.5.1
  shared_preferences: ^0.5.3+4
  fluttertoast: ^3.1.3
  flutter_cipher: ^0.0.3
  crypto: ^2.1.2
  cipher2: ^0.3.5
  utf: ^0.9.0+5
  flutter_screenutil: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

